---
title: "R-based Clinical Trial Regulatory Submission Working Group"
description: |
  The R submission working group is a cross industry pharma working group
  focusing on improving practices of R-based 
  clinical trial regulatory submission. 
  The R submission working group is under R consortium.
site: distill::distill_website
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)

# Learn more about creating websites with Distill at:
# https://rstudio.github.io/distill/website.html

```

# Our Mission

- Easier R-based clinical trial regulatory submissions today
  - by showing open examples of using current submission portals
- Easier R-based clinical trial regulatory submissions tomorrow
  - by collecting feedback and influencing future industry and agency decisions on system/process setup



```{r child="pilot-overall.Rmd", echo=FALSE}
```

```{r child="pilot1-overall.Rmd", echo=FALSE}
```

```{r child="pilot2-overall.Rmd", echo=FALSE}
```

```{r child="pilot3-overall.Rmd", echo=FALSE}
```